### ISSUE TITLE
Have green baby balloon for yellow + blue balloon collision

### ISSUE THREAD

**Issue by iryanclarke** [screaming-goat/the-game#110] opened 2015-04-14 03:09 UTC
Right now there is only yellow + blue baby balloons, but if yellow and blue combine it needs to make a green one

**Comment by kieralundberg** [comment] 2015-04-14 10:16
There are green baby balloons. Please check the work completed last week

**Comment by iryanclarke** [comment] 2015-04-14 13:14
Ah it was? My bad, I was just going off the stuff I saw in the baby balloon colour detection/ etc

**Comment by teganscott** [comment] 2015-04-14 16:30
This is not an enhancement, this is something that was written in our design document.

**Comment by teganscott** [comment] 2015-04-14 17:20
Duplicate of task #83
Estimated Time: N/A
Actual Time: N/A

**Closed as completed** 2015-04-14 17:20 UTC
Labels: duplicate
